// <auto-generated />
namespace DogBirthday.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addbuttonforbreed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addbuttonforbreed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704141510217_add-button-for-breed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
